# Lab07

The lab involves:
1. Simulate files containing random DNA, protein, and binary data
2. Compressing the data
3. Comparing between different compressions and sequences
4. Compressing real data
5. Estimating compression of 1000 terabytes

## 1. Simulate files containing random DNA, protein, and binary data
Using **np.random.choice**,  100 megabytes(8 bits/byte* 1024 bytes/kilobyte* 1024 kilobytes/megabyte* 100)of random data was generated containing 100%, 90%, 80%, 70%, 60%, and 50% zeroes.

In [11]:
import numpy as np

#100 megabytes of random data containing 100% zeroes
hundred= np.random.choice([0, 1], size=[800000000], replace=True, p=[1, 0.0])
hundred = np.packbits(hundred)
print(hundred)
open("zeros_100p", "wb").write(hundred)

[0 0 0 ... 0 0 0]


100000000

In [9]:
#100 megabytes of random data containing 90% zeroes
ninety= np.random.choice([0, 1], size=[800000000], replace=True, p=[0.9, 0.1])
ninety = np.packbits(ninety)
print(ninety)
open("zeros_90p", "wb").write(ninety)

[8 2 0 ... 0 0 0]


100000000

In [10]:
#100 megabytes of random data containing 80% zeroes
eighty= np.random.choice([0, 1], size=[800000000], replace=True, p=[0.8, 0.2])
eighty = np.packbits(eighty)
print(eighty)
open("zeros_80p", "wb").write(eighty)

[ 52   4 161 ...  16   9  18]


100000000

In [4]:
#100 megabytes of random data containing 70% zeroes
seventy= np.random.choice([0, 1], size=[800000000], replace=True, p=[0.7, 0.3])
seventy = np.packbits(seventy)
print(seventy)
open("zeros_70p", "wb").write(seventy)

[  0  67 100 ...   2 128 174]


100000000

In [5]:
#100 megabytes of random data containing 60% zeroes
sixty= np.random.choice([0, 1], size=[800000000], replace=True, p=[0.6, 0.4])
sixty = np.packbits(sixty)
print(sixty)
open("zeros_60p", "wb").write(sixty)

[ 89 222  52 ...  38 220   5]


100000000

In [6]:
#100 megabytes of random data containing 50% zeroes
fifty = np.random.choice([0, 1], size=[800000000], replace=True, p=[0.5, 0.5])
fifty = np.packbits(fifty)
print(fifty)
open("zeros_50p", "wb").write(fifty)

[  0  80  89 ...  45 199  48]


100000000

In [20]:
#100 megabytes of random DNA sequence
dna = np.random.choice(['A', 'C', 'T', 'G'], size=100000000, replace=True, p=[0.25, 0.25, 0.25, 0.25])
print(dna)
open("nt_seq.fa", "w").write("".join(dna))

['G' 'T' 'G' ... 'T' 'G' 'A']


100000000

In [21]:
#100 megabytes of random protein sequence
pro = np.random.choice(['G','A','L','M','A','W','K','Q','E','S','P','V','I','C','Y','H','R','N','D','T'],
                       size=[100000000], replace=True, p=[0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
                                                          0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
                                                          0.05, 0.05, ])
print(pro)
open("pro_seq.fa", "w").write("".join(pro))

['N' 'G' 'M' ... 'Y' 'A' 'L']


100000000

# 2. Compressing the data

Each of the files generated above was compressed by running **gzip**, **bzip**, **pbzip2** and **ArithmeticCompress** in the terminal. 

The size of the input files, output files, and the time each command took to run was recorded in the table below:

zeros_100p 

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k zeros_100p  | zeros_100p.gz | 97.1k | 0.688|
| `bzip`    | time bzip2 -k zeros_100p  | zeros_100p1.bz2 | 113 | 1.010 |
| `pbzip2`    | time pbzip2 -k zeros_100p |zeros_100p.bz2 |5.38k | 0.104 |
| `ArithmeticCompress`  | time ArithmeticCompress zeros_100p zeros_100p.art |zeros_100p.art | 1.03k | 14.176|

zeros_90p 

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k zeros_90p  | zeros_90p.gz | 56M | 18.070|
| `bzip`    | time bzip2 -k zeros_90p  | zeros_90p1.bz2 | 58.3M | 10.159 |
| `pbzip2`    | time pbzip2 -k zeros_90p |zeros_90p.bz2 |58.3M | 0.736 |
| `ArithmeticCompress`  | time ArithmeticCompress zeros_90p zeros_90p.art |zeros_90p.art | 46.9M | 0.196|

zeros_80p 

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k zeros_80p  | zeros_80p.gz | 77.4M | 12.989|
| `bzip`    | time bzip2 -k zeros_80p  | zeros_80p1.bz2 | 82.6M | 11.598|
| `pbzip2`    | time pbzip2 -k zeros_80p |zeros_80p.bz2 | 82.6M| 0.936 |
| `ArithmeticCompress`  | time ArithmeticCompress zeros_80p zeros_80p.art |zeros_80p.art | 15.9M | 33.824|

zeros_70p 

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k zeros_70p  | zeros_70p.gz | 89.3M | 6.185|
| `bzip`    | time bzip2 -k zeros_70p  | zeros_70p1.bz2 | 95.1M | 13.198|
| `pbzip2`    | time pbzip2 -k zeros_70p |zeros_70p.bz2 |95.1M | 1.113 |
| `ArithmeticCompress`  | time ArithmeticCompress zeros_70p zeros_70p.art |zeros_70p.art | 88.1M | 37.687|

zeros_60p 

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k zeros_60p  | zeros_60p.gz | 97.7M | 4.079|
| `bzip`    | time bzip2 -k zeros_60p  | zeros_60p1.bz2 | 100M | 14.992 |
| `pbzip2`    | time pbzip2 -k zeros_60p |zeros_60p.bz2 |100M | 1.308 |
| `ArithmeticCompress`  | time ArithmeticCompress zeros_60p zeros_60p.art |zeros_60p.art | 97.1M | 39.078|

zeros_50p 

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k zeros_50p  | zeros_50p.gz | 100M | 3.398|
| `bzip`    | time bzip2 -k zeros_50p  | zeros_50p1.bz2 | 100M | 15.858 |
| `pbzip2`    | time pbzip2 -k zeros_50p |zeros_50p.bz2 |100M | 1.388 |
| `ArithmeticCompress`  | time ArithmeticCompress zeros_50p zeros_50p.art |zeros_50p.art | 100M| 39.414|

nt_seq.fa

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k nt_seq.fa  | nt_seq.fa.gz  | 29.2M | 12.149|
| `bzip`    | time bzip2 -k nt_seq.fa  | nt_seq.fa1.bz2 | 27.3M | 9.458|
| `pbzip2`    | time pbzip2 -k nt_seq.fa |nt_seq.fa.bz2 |27.3M | 0.690 |
| `ArithmeticCompress`  | time ArithmeticCompress nt_seq.fa nt_seq.art |nt_seq.art | 25M| 22.216|

pro_seq.fa

|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k pro_seq.fa  | pro_seq.fa.gz  | 59.5M | 4.492|
| `bzip`    | time bzip2 -k pro_seq.fa  | pro_seq.fa1.bz2 | 54.2M | 9.915|
| `pbzip2`    | time pbzip2 -k pro_seq.fa |pro_seq.fa.bz2 |54.2M | 0.786 |
| `ArithmeticCompress`  | time ArithmeticCompress pro_seq.fa pro_seq.art |pro_seq.art | 52.8M| 28.315|


# 3. Comparing between different compressions and sequences

## Which algorithm achieves the best level of compression on each file type?
`ArithmeticCompress` achieved the best level of compression on each file type, as shown in the table above. For each type of file, the file compressed by `ArithmeticCompress` is the smallest. Except for compression of _zeros_50p_, which may be because the data was in a uniform binary distribution. `ArithmeticCompress` is only more effective(archieves Shannon limit) if there is an algorithm to predict next character in the sequence.

## Which algorithm is the fastest?
`pbzip2` is the fastest, as it used the least real time, which is made up by sum of user and system time.

## What is the difference between bzip2 and pbzip2? Do you expect one to be faster and why?
Except for file zeros_100p, file compressed by `pbzip2` is always the same as compression of `bzip`. `pbzip2` compression is faster than `bzip` compression. I did not expect `pbzip2` to be faster, it is a version of `bzip2` that does parallel processing. 

## How does the level of compression change as the percentage of zeros increases?Why does this happen?
As the percentage of zeroes increase, the level of compression becomes higher - the file with more zeroes can be compressed into a smaller file. The higher percentage of zeroes in the file, the lower percentages of numbers other than 0 exist in the same file, and the less the types of numbers exist in each file. It will be easier to compress because the more number of zeroes in the file(higher zero percentage means more zero will be "selected" to be in the file), the more likely is there to be a patten of zeroes generated, which is easier to store and increases the level of compression.

## What is the minimum number of bits required to store a single DNA base?
Bits needed = -log(number of possible nucleotides) in base 2
There are 4 possible nucleotides: A, T, G, C
Bits needed = log(4) in base 2
            = 2 bits
            
## What is the minimum number of bits required to store an amino acid letter?            
Bits needed = -log(number of possible amino acids) in base 2
There are 20 possible nucleotides.
Bits needed = log(20) in base 2
            = 4.321 bits
                        
## In your tests, how many bits did gzip and bzip2 actually require to store your random DNA and protein sequences?
For random DNA sequences, `gzip` needed 29.2MB and `bzip2` needed 27.3MB.
For random protein sequences, `gzip` needed 59.5MB and `bzip2` needed 54.2MB.

## Are gzip and bzip2 performing well on DNA and proteins?
Yes. The initial DNA and protein sequences are 100MB each, and there is a great drop in the size of the file after compression. Both `gzip1` and `bzip` works better on DNA sequences because there is less number of variables (4 nucleotides thus 4 possiblities for each DNA letter) as compared to the 20 letters of amino acids in the random protein sequence.

# 4. Compressing real data

The nucleic acid sequences of gp120 homologs from 10 different HIV isolates were discovered with the GSI Michael [here](https://www.hiv.lanl.gov/cgi-bin/NEWALIGN/align.cgi). They were being copied and pasted into a text file,"a.txt", and some modifications were done.

In [65]:
# Remove any dashes due to alignments 
import re
string = open('a.txt').read()
new_str = re.sub('[^a-zA-Z0-9_.>]', '', string)
open('b.fa', 'w').write("".join(new_str))

# A line break between was put between every nucleic acid sequence

15566

## Compressing the multi-FASTA using gzip, bzip2, and arithmetic coding
At priori, I expected there to be better compression than some of the random data(such as random protein sequence), because most of the homologs of HIV share similar sequences

The table below shows the result of compression of the homolog:

b.fa is 15.6 kB


|Compression used | Command ran on terminal| Compressed File name | Compressed File Size(B) | Real Time used(s)|
|:-----------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | time gzip -k b.fa  | b.fa.gz | 3.63k | 0.005|
| `bzip`    | time bzip2 -k b.fa  | b1.fa.bz2 | 3.52k | 0.008 |
| `pbzip2`    | time pbzip2 -k b.fa |b.fa.bz2 | 3.52k | 0.011 |
| `ArithmeticCompress`  | time ArithmeticCompress b.fa b.art | b.art | 5.15k | 0.016|


### How does the compression ratio of this file compare to random data?
Compression ratio = Inital file size/Compressed file size

Compression ratio of  b.fa

|Compression used| Inital file | Compressed file | Inital file size(B)| Compressed File Size(B)|Compression ratio|
|:-----------|:-------------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | b.fa | b.fa.gz | 15.6k| 3.63k | 4.298|
| `bzip`    | b.fa  | b1.fa.bz2 | 15.6k|3.52k | 4.432 |
| `pbzip2`    | b.fa |b.fa.bz2 | 15.6k| 3.52k | 4.432 |
| `ArithmeticCompress`  | b.fa | b.art | 15.6k | 5.15k| 3.029 |
| Average Compression Ratio of b.fa ||||| 4.048|


Compression ratio of nt_seq.fa

|Compression used| Inital file | Compressed file | Inital file size(B)| Compressed File Size(B)|Compression ratio|
|:-----------|:-------------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | nt_seq.fa | nt_seq.gz | 100M | 29.2M | 3.425|
| `bzip`    | nt_seq.fa  | nt_seq.bz2 | 100M| 27.3M | 3.663 |
| `pbzip2`    | nt_seq.fa |nt_seq.bz2 | 100M| 27.3M | 3.663 |
| `ArithmeticCompress`  | b.fa | nt_seq.art | 100M | 25M | 4 |
| Average Compression Ratio of nt_seq.fa ||||| 3.688|

Compression ratio of pro_seq.fa

|Compression used| Inital file | Compressed file | Inital file size(B)| Compressed File Size(B)|Compression ratio|
|:-----------|:-------------|:-------------|:-------------|:-------------|:-------------|
| `gzip`     | pro_seq.fa | pro_seq.gz | 100M | 59.5M | 1.681|
| `bzip`    | pro_seq.fa  | pro_seq.bz2 | 100M| 54.2M | 1.845 |
| `pbzip2`    | pro_seq.fa |pro_seq.bz2 | 100M| 54.2M | 1.845 |
| `ArithmeticCompress`  | pro_seq.fa | pro_seq.art | 100M | 52.8M | 1.894 |
| Average Compression Ratio of pro_seq.fa||||| 4.048|


We can see that on average, the compression of the homolog fasta file is greater than the random DNA and protein sequences, for different compression computations. 


# 5. Estimating compression of 1000 terabytes

* $50 per terabyte of hard disk space
* My team willget a bonus this year equal to the amount of savings we’re able to generate by compressing the company’s data

I propose using `bzip` for re-sequencing of genomes and plasmids that are very similar to each other. As we can see from the compression ratio table above, the compression ratio is the highest using `bzip` and `pbzip` when we are compressing **homologs**, a gene related to a second gene by descent from a common ancestral DNA sequence. This means that compressing similar sequences, `bzip` and `pbzip` gives the best compression results. `bzip` was prefered because `pbzip` used longer time. `bizip` can also be used if the protein sequences are similar. `bzip` uses **Burrows-Wheeler transformation**, which means that the repeated subtrings will show up as **repeated characters** after rotations of input string, causing it to be encoded and compressed much more effectively.

I propose using `ArithmeticCompress` for compressing protein sequences and binary microscope images which, assuming follow the worst-case scenario of being completely random. As we can see from the compression ratio tables above, the compression ratio is the highest using `ArithmeticCompress` when we are compressing random sequences.

## Estimate for the fraction of space saved using the above compression scheme
For using `bzip` to compress re-sequencing of genomes and plasmids that are very similar to each other, according to the compression table, I can round down and assume the compression ratio of `bzip` for similar sequences is 4. Thus if 1000 terabytes were compressed to a file 4 times smaller to 250 terabytes, the company saved 750 terabytes. The 75percent reduction can generate 75percentx500 dollarsx365 days = 13687500 dollars bonus per year. 

For using `ArithmeticCompress` to compress protein sequences, according to the compression table for protein sequence(assuming follow the worst-case scenario of being completely random), I assume the compression ratio of `bzip` for random protein sequences is 4. Thus if 1000 terabytes were compressed to a file 4 times smaller to 250 terabytes, the company saved 750 terabytes. The 75percent reduction can generate 75x500 dollarsx365 days = 13687500 dollars bonus per year. 

Assuming the binary microscope images are completely random, compression may not be possible, modeled by the zeros_50p table above.


Estimated total bonus this year= 13687500 dollars + 13687500 dollars 
                               = 27375000 dollars
                               
This estimation is **highly inaccurate** because the compression really depends on the type of sequences and files obtained by the company, of which the randomness or uniqueness of the sequences are not definite. Compressions of these files will also have _different compression ratios_ and generate _different type of files_ as required so the percentage of compression is indefinite as well. 